version: '3.9'

services:
  # Контейнер клиента
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client/src:/client/src'
      - './client/public:/client/public'
    ports:
      - "5001:3000"

  # Контейнер сервера
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: node app.js
    ports:
      - "5000:8089"
    container_name: impuls-game-server
    depends_on:
      - postgres-db

  # Контейнер бд 
  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "8089:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  # PgAdmin 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@example.com"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    expose:
      - '80'
    depends_on:
      - postgres-db

  # Nginx
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"